[package]
name = "hello_macro_derive"
version = "0.1.0"
authors = ["Jeff Goldschrafe <jeff@holyhandgrenade.org>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.14.4"
quote = "0.6.3"
